//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Camera
{
    [Serializable]
    public class CameraCompressedImageMsg : Message
    {
        public const string k_RosMessageName = "camera_msgs/CameraCompressedImage";
        public override string RosMessageName => k_RosMessageName;

        //  camera_msgs/msg/CameraImage.msg
        public Sensor.CompressedImageMsg image;
        public string camera_id;

        public CameraCompressedImageMsg()
        {
            this.image = new Sensor.CompressedImageMsg();
            this.camera_id = "";
        }

        public CameraCompressedImageMsg(Sensor.CompressedImageMsg image, string camera_id)
        {
            this.image = image;
            this.camera_id = camera_id;
        }

        public static CameraCompressedImageMsg Deserialize(MessageDeserializer deserializer) => new CameraCompressedImageMsg(deserializer);

        private CameraCompressedImageMsg(MessageDeserializer deserializer)
        {
            this.image = Sensor.CompressedImageMsg.Deserialize(deserializer);
            deserializer.Read(out this.camera_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.image);
            serializer.Write(this.camera_id);
        }

        public override string ToString()
        {
            return "CameraCompressedImageMsg: " +
            "\nimage: " + image.ToString() +
            "\ncamera_id: " + camera_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
